"""
API scope definitions and utilities for Falcon MCP Server

This module provides API scope definitions and related utilities for the Falcon MCP server.
"""

from .logging import get_logger

logger = get_logger(__name__)

# Map of API operations to required scopes
# This can be expanded as more modules and operations are added
API_SCOPE_REQUIREMENTS = {
    # Alerts operations (migrated from detections)
    "GetQueriesAlertsV1": ["Alerts:read"],
    "GetQueriesAlertsV2": ["Alerts:read"],
    "PostCombinedAlertsV1": ["Alerts:read"],
    "PostAggregatesAlertsV1": ["Alerts:read"],
    "PostAggregatesAlertsV2": ["Alerts:read"],
    "PostEntitiesAlertsV1": ["Alerts:read"],
    "PostEntitiesAlertsV2": ["Alerts:read"],
    "PatchEntitiesAlertsV1": ["Alerts:write"],
    "PatchEntitiesAlertsV2": ["Alerts:write"],
    "PatchEntitiesAlertsV3": ["Alerts:write"],
    # Hosts operations
    "QueryDevicesByFilter": ["Hosts:read"],
    "PostDeviceDetailsV2": ["Hosts:read"],
    # Host Groups operations
    "queryHostGroups": ["Host Groups:read"],
    "getHostGroups": ["Host Groups:read"],
    "queryCombinedGroupMembers": ["Host Groups:read"],
    "createHostGroups": ["Host Groups:write"],
    "updateHostGroups": ["Host Groups:write"],
    "deleteHostGroups": ["Host Groups:write"],
    "performGroupAction": ["Host Groups:write"],
    # Host Migration operations
    "GetMigrationIDsV1": ["Host Migration:read"],
    "GetMigrationsV1": ["Host Migration:read"],
    "GetHostMigrationIDsV1": ["Host Migration:read"],
    "GetHostMigrationsV1": ["Host Migration:read"],
    "GetMigrationDestinationsV1": ["Host Migration:read"],
    "CreateMigrationV1": ["Host Migration:write"],
    "MigrationsActionsV1": ["Host Migration:write"],
    "HostMigrationsActionsV1": ["Host Migration:write"],
    # IT Automation operations
    "ITAutomationGetAssociatedTasks": ["IT Automation:read"],
    "ITAutomationCombinedScheduledTasks": ["IT Automation:read"],
    "ITAutomationGetTaskExecutionsByQuery": ["IT Automation:read"],
    "ITAutomationGetTaskGroupsByQuery": ["IT Automation:read"],
    "ITAutomationGetTasksByQuery": ["IT Automation:read"],
    "ITAutomationGetUserGroup": ["IT Automation:read"],
    "ITAutomationCreateUserGroup": ["IT Automation:write"],
    "ITAutomationUpdateUserGroup": ["IT Automation:write"],
    "ITAutomationDeleteUserGroup": ["IT Automation:write"],
    "ITAutomationRunLiveQuery": ["IT Automation:write"],
    "ITAutomationUpdatePolicyHostGroups": ["IT Automation:write"],
    "ITAutomationUpdatePoliciesPrecedence": ["IT Automation:write"],
    "ITAutomationGetPolicies": ["IT Automation:read"],
    "ITAutomationCreatePolicy": ["IT Automation:write"],
    "ITAutomationUpdatePolicies": ["IT Automation:write"],
    "ITAutomationDeletePolicy": ["IT Automation:write"],
    "ITAutomationGetScheduledTasks": ["IT Automation:read"],
    "ITAutomationCreateScheduledTask": ["IT Automation:write"],
    "ITAutomationUpdateScheduledTask": ["IT Automation:write"],
    "ITAutomationDeleteScheduledTasks": ["IT Automation:write"],
    "ITAutomationCancelTaskExecution": ["IT Automation:write"],
    "ITAutomationGetTaskExecutionHostStatus": ["IT Automation:read"],
    "ITAutomationRerunTaskExecution": ["IT Automation:write"],
    "ITAutomationGetExecutionResultsSearchStatus": ["IT Automation:read"],
    "ITAutomationStartExecutionResultsSearch": ["IT Automation:read"],
    "ITAutomationGetExecutionResults": ["IT Automation:read"],
    "ITAutomationGetTaskExecution": ["IT Automation:read"],
    "ITAutomationStartTaskExecution": ["IT Automation:write"],
    "ITAutomationGetTaskGroups": ["IT Automation:read"],
    "ITAutomationCreateTaskGroup": ["IT Automation:write"],
    "ITAutomationUpdateTaskGroup": ["IT Automation:write"],
    "ITAutomationDeleteTaskGroups": ["IT Automation:write"],
    "ITAutomationGetTasks": ["IT Automation:read"],
    "ITAutomationCreateTask": ["IT Automation:write"],
    "ITAutomationUpdateTask": ["IT Automation:write"],
    "ITAutomationDeleteTask": ["IT Automation:write"],
    "ITAutomationSearchUserGroup": ["IT Automation:read"],
    "ITAutomationQueryPolicies": ["IT Automation:read"],
    "ITAutomationSearchScheduledTasks": ["IT Automation:read"],
    "ITAutomationSearchTaskExecutions": ["IT Automation:read"],
    "ITAutomationSearchTaskGroups": ["IT Automation:read"],
    "ITAutomationSearchTasks": ["IT Automation:read"],
    # Incidents operations
    "QueryIncidents": ["Incidents:read"],
    "CrowdScore": ["Incidents:read"],
    "GetIncidents": ["Incidents:read"],
    "GetBehaviors": ["Incidents:read"],
    "QueryBehaviors": ["Incidents:read"],
    "PerformIncidentAction": ["Incidents:write"],
    # Intel operations
    "QueryIntelActorIds": ["Actors (Falcon Intelligence):read"],
    "QueryIntelActorEntities": ["Actors (Falcon Intelligence):read"],
    "GetIntelActorEntities": ["Actors (Falcon Intelligence):read"],
    "QueryIntelIndicatorIds": ["Indicators (Falcon Intelligence):read"],
    "QueryIntelIndicatorEntities": ["Indicators (Falcon Intelligence):read"],
    "GetIntelIndicatorEntities": ["Indicators (Falcon Intelligence):read"],
    "QueryIntelReportIds": ["Reports (Falcon Intelligence):read"],
    "QueryIntelReportEntities": ["Reports (Falcon Intelligence):read"],
    "GetIntelReportEntities": ["Reports (Falcon Intelligence):read"],
    "GetIntelReportPDF": ["Reports (Falcon Intelligence):read"],
    "QueryIntelRuleIds": ["Reports (Falcon Intelligence):read"],
    "GetIntelRuleEntities": ["Reports (Falcon Intelligence):read"],
    "GetIntelRuleFile": ["Reports (Falcon Intelligence):read"],
    "GetLatestIntelRuleFile": ["Reports (Falcon Intelligence):read"],
    "QueryMalware": ["Reports (Falcon Intelligence):read"],
    "QueryMalwareEntities": ["Reports (Falcon Intelligence):read"],
    "GetMalwareEntities": ["Reports (Falcon Intelligence):read"],
    "GetMalwareMitreReport": ["Reports (Falcon Intelligence):read"],
    "QueryMitreAttacks": ["Actors (Falcon Intelligence):read"],
    "QueryMitreAttacksForMalware": ["Reports (Falcon Intelligence):read"],
    "PostMitreAttacks": ["Actors (Falcon Intelligence):read"],
    "QueryVulnerabilities": ["Indicators (Falcon Intelligence):read"],
    "GetVulnerabilities": ["Indicators (Falcon Intelligence):read"],
    "GetMitreReport": ["Actors (Falcon Intelligence):read"],
    # IOC operations
    "indicator_search_v1": ["IOC Management:read"],
    "indicator_get_v1": ["IOC Management:read"],
    "indicator_create_v1": ["IOC Management:write"],
    "indicator_delete_v1": ["IOC Management:write"],
    # IOA Exclusions operations
    "queryIOAExclusionsV1": ["IOA Exclusions:read"],
    "getIOAExclusionsV1": ["IOA Exclusions:read"],
    "createIOAExclusionsV1": ["IOA Exclusions:write"],
    "updateIOAExclusionsV1": ["IOA Exclusions:write"],
    "deleteIOAExclusionsV1": ["IOA Exclusions:write"],
    # Firewall Management operations
    "aggregate_events": ["Firewall Management:read"],
    "aggregate_policy_rules": ["Firewall Management:read"],
    "aggregate_rule_groups": ["Firewall Management:read"],
    "aggregate_rules": ["Firewall Management:read"],
    "get_events": ["Firewall Management:read"],
    "get_firewall_fields": ["Firewall Management:read"],
    "get_network_locations": ["Firewall Management:read"],
    "get_network_locations_details": ["Firewall Management:read"],
    "get_platforms": ["Firewall Management:read"],
    "get_policy_containers": ["Firewall Management:read"],
    "create_network_locations": ["Firewall Management:write"],
    "query_rules": ["Firewall Management:read"],
    "get_rules": ["Firewall Management:read"],
    "query_rule_groups": ["Firewall Management:read"],
    "get_rule_groups": ["Firewall Management:read"],
    "query_policy_rules": ["Firewall Management:read"],
    "query_events": ["Firewall Management:read"],
    "query_firewall_fields": ["Firewall Management:read"],
    "query_network_locations": ["Firewall Management:read"],
    "query_platforms": ["Firewall Management:read"],
    "upsert_network_locations": ["Firewall Management:write"],
    "update_network_locations": ["Firewall Management:write"],
    "update_network_locations_metadata": ["Firewall Management:write"],
    "update_network_locations_precedence": ["Firewall Management:write"],
    "update_policy_container": ["Firewall Management:write"],
    "update_policy_container_v1": ["Firewall Management:write"],
    "create_rule_group": ["Firewall Management:write"],
    "create_rule_group_validation": ["Firewall Management:write"],
    "update_rule_group": ["Firewall Management:write"],
    "update_rule_group_validation": ["Firewall Management:write"],
    "delete_network_locations": ["Firewall Management:write"],
    "delete_rule_groups": ["Firewall Management:write"],
    "validate_filepath_pattern": ["Firewall Management:read"],
    # Real Time Response operations
    "RTR_AggregateSessions": ["Real Time Response:read"],
    "BatchActiveResponderCmd": ["Real Time Response:read"],
    "BatchCmd": ["Real Time Response:read"],
    "BatchGetCmdStatus": ["Real Time Response:read"],
    "BatchGetCmd": ["Real Time Response:read"],
    "BatchInitSessions": ["Real Time Response:read"],
    "BatchRefreshSessions": ["Real Time Response:read"],
    "RTR_CheckActiveResponderCommandStatus": ["Real Time Response:read"],
    "RTR_ExecuteActiveResponderCommand": ["Real Time Response:read"],
    "RTR_GetExtractedFileContents": ["Real Time Response:read"],
    "RTR_ListFiles": ["Real Time Response:read"],
    "RTR_DeleteFile": ["Real Time Response:read"],
    "RTR_ListFilesV2": ["Real Time Response:read"],
    "RTR_DeleteFileV2": ["Real Time Response:read"],
    "RTR_ListQueuedSessions": ["Real Time Response:read"],
    "RTR_PulseSession": ["Real Time Response:read"],
    "RTR_ListAllSessions": ["Real Time Response:read"],
    "RTR_ListSessions": ["Real Time Response:read"],
    "RTR_InitSession": ["Real Time Response:read"],
    "RTR_ExecuteCommand": ["Real Time Response:read"],
    "RTR_CheckCommandStatus": ["Real Time Response:read"],
    "RTR_DeleteSession": ["Real Time Response:read"],
    "RTR_DeleteQueuedSession": ["Real Time Response:read"],
    # Real Time Response Admin operations
    "RTR_ListScripts": ["Real Time Response Admin:write"],
    "RTR_GetScripts": ["Real Time Response Admin:write"],
    "RTR_GetFalconScripts": ["Real Time Response Admin:write"],
    "RTR_GetPutFileContents": ["Real Time Response Admin:write"],
    "RTR_ListPut_Files": ["Real Time Response Admin:write"],
    "RTR_GetPut_Files": ["Real Time Response Admin:write"],
    "RTR_CreatePut_Files": ["Real Time Response Admin:write"],
    "RTR_DeletePut_Files": ["Real Time Response Admin:write"],
    "RTR_GetPut_FilesV2": ["Real Time Response Admin:write"],
    "RTR_CreatePut_FilesV2": ["Real Time Response Admin:write"],
    "RTR_CreateScripts": ["Real Time Response Admin:write"],
    "RTR_UpdateScripts": ["Real Time Response Admin:write"],
    "RTR_DeleteScripts": ["Real Time Response Admin:write"],
    "RTR_GetScriptsV2": ["Real Time Response Admin:write"],
    "RTR_CreateScriptsV2": ["Real Time Response Admin:write"],
    "RTR_UpdateScriptsV2": ["Real Time Response Admin:write"],
    "RTR_ListFalconScripts": ["Real Time Response Admin:write"],
    "RTR_ExecuteAdminCommand": ["Real Time Response Admin:write"],
    "RTR_CheckAdminCommandStatus": ["Real Time Response Admin:write"],
    "BatchAdminCmd": ["Real Time Response Admin:write"],
    # Real Time Response Audit operations
    "RTRAuditSessions": ["Real Time Response Audit:read"],
    # Spotlight operations
    "combinedQueryVulnerabilities": ["Vulnerabilities:read"],
    "queryVulnerabilities": ["Vulnerabilities:read"],
    "getVulnerabilities": ["Vulnerabilities:read"],
    "getRemediations": ["Vulnerabilities:read"],
    "getRemediationsV2": ["Vulnerabilities:read"],
    # Discover operations
    "combined_applications": ["Assets:read"],
    "combined_hosts": ["Assets:read"],
    "query_accounts": ["Assets:read"],
    "query_applications": ["Assets:read"],
    "query_hosts": ["Assets:read"],
    "query_iot_hosts": ["Assets:read"],
    "query_iot_hostsV2": ["Assets:read"],
    "query_logins": ["Assets:read"],
    "get_accounts": ["Assets:read"],
    "get_applications": ["Assets:read"],
    "get_hosts": ["Assets:read"],
    "get_iot_hosts": ["Assets:read"],
    "get_logins": ["Assets:read"],
    # Exposure Management operations
    "query_external_assets_v2": ["Exposure Management:read"],
    "get_external_assets": ["Exposure Management:read"],
    "aggregate_external_assets": ["Exposure Management:read"],
    "post_external_assets_inventory_v1": ["Exposure Management:write"],
    "patch_external_assets": ["Exposure Management:write"],
    "delete_external_assets": ["Exposure Management:write"],
    # CAO Hunting operations
    "AggregateHuntingGuides": ["CAO Hunting:read"],
    "AggregateIntelligenceQueries": ["CAO Hunting:read"],
    "GetArchiveExport": ["CAO Hunting:read"],
    "GetHuntingGuides": ["CAO Hunting:read"],
    "GetIntelligenceQueries": ["CAO Hunting:read"],
    "SearchHuntingGuides": ["CAO Hunting:read"],
    "SearchIntelligenceQueries": ["CAO Hunting:read"],
    # Zero Trust Assessment operations
    "getAssessmentV1": ["Zero Trust Assessment:read"],
    "getAuditV1": ["Zero Trust Assessment:read"],
    "getAssessmentsByScoreV1": ["Zero Trust Assessment:read"],
    "getCombinedAssessmentsQuery": ["Zero Trust Assessment:read"],
    # Cloud operations
    "ReadContainerCombined": ["Falcon Container Image:read"],
    "ReadContainerCount": ["Falcon Container Image:read"],
    "ReadCombinedVulnerabilities": ["Falcon Container Image:read"],
    "ReadCombinedVulnerabilitiesDetails": ["Falcon Container Image:read"],
    "ReadCombinedVulnerabilitiesInfo": ["Falcon Container Image:read"],
    "ReadVulnerabilityCount": ["Falcon Container Image:read"],
    "ReadVulnerabilityCountBySeverity": ["Falcon Container Image:read"],
    "ReadVulnerabilityCountByCPSRating": ["Falcon Container Image:read"],
    "ReadVulnerabilityCountByCVSSScore": ["Falcon Container Image:read"],
    "ReadVulnerabilityCountByActivelyExploited": ["Falcon Container Image:read"],
    "ReadVulnerabilitiesByImageCount": ["Falcon Container Image:read"],
    "ReadVulnerabilitiesPublicationDate": ["Falcon Container Image:read"],
    # Identity Protection operations
    "api_preempt_proxy_post_graphql": [
        "Identity Protection Entities:read",
        "Identity Protection Timeline:read",
        "Identity Protection Detections:read",
        "Identity Protection Assessment:read",
        "Identity Protection GraphQL:write",
    ],
    # User Management operations
    "aggregateUsersV1": ["User Management:read"],
    "queryUserV1": ["User Management:read"],
    "retrieveUsersGETV1": ["User Management:read"],
    "queriesRolesV1": ["User Management:read"],
    "entitiesRolesGETV2": ["User Management:read"],
    "entitiesRolesV1": ["User Management:read"],
    "CombinedUserRolesV2": ["User Management:read"],
    "createUserV1": ["User Management:write"],
    "updateUserV1": ["User Management:write"],
    "deleteUserV1": ["User Management:write"],
    "userActionV1": ["User Management:write"],
    "userRolesActionV1": ["User Management:write"],
    # Sensor Usage operations
    "GetSensorUsageWeekly": ["Sensor Usage:read"],
    # Sensor Download operations
    "GetCombinedSensorInstallersByQuery": ["Sensor Download:read"],
    "GetCombinedSensorInstallersByQueryV2": ["Sensor Download:read"],
    "DownloadSensorInstallerById": ["Sensor Download:read"],
    "DownloadSensorInstallerByIdV2": ["Sensor Download:read"],
    "GetSensorInstallersEntities": ["Sensor Download:read"],
    "GetSensorInstallersEntitiesV2": ["Sensor Download:read"],
    "GetSensorInstallersCCIDByQuery": ["Sensor Download:read"],
    "GetSensorInstallersByQuery": ["Sensor Download:read"],
    "GetSensorInstallersByQueryV2": ["Sensor Download:read"],
    # Installation Tokens operations
    "audit_events_read": ["Installation Tokens:read"],
    "customer_settings_read": ["Installation Tokens:read"],
    "tokens_read": ["Installation Tokens:read"],
    "audit_events_query": ["Installation Tokens:read"],
    "tokens_query": ["Installation Tokens:read"],
    "tokens_create": ["Installation Tokens:write"],
    "tokens_delete": ["Installation Tokens:write"],
    "tokens_update": ["Installation Tokens:write"],
    "customer_settings_update": ["Installation Tokens Settings:write"],
    # Sensor Update Policies operations
    "revealUninstallToken": ["Sensor Update Policies:write"],
    "queryCombinedSensorUpdateBuilds": ["Sensor Update Policies:read"],
    "queryCombinedSensorUpdateKernels": ["Sensor Update Policies:read"],
    "queryCombinedSensorUpdatePolicyMembers": ["Sensor Update Policies:read"],
    "queryCombinedSensorUpdatePolicies": ["Sensor Update Policies:read"],
    "queryCombinedSensorUpdatePoliciesV2": ["Sensor Update Policies:read"],
    "performSensorUpdatePoliciesAction": ["Sensor Update Policies:write"],
    "setSensorUpdatePoliciesPrecedence": ["Sensor Update Policies:write"],
    "getSensorUpdatePolicies": ["Sensor Update Policies:read"],
    "createSensorUpdatePolicies": ["Sensor Update Policies:write"],
    "updateSensorUpdatePolicies": ["Sensor Update Policies:write"],
    "deleteSensorUpdatePolicies": ["Sensor Update Policies:write"],
    "getSensorUpdatePoliciesV2": ["Sensor Update Policies:read"],
    "createSensorUpdatePoliciesV2": ["Sensor Update Policies:write"],
    "updateSensorUpdatePoliciesV2": ["Sensor Update Policies:write"],
    "querySensorUpdateKernelsDistinct": ["Sensor Update Policies:read"],
    "querySensorUpdatePolicyMembers": ["Sensor Update Policies:read"],
    "querySensorUpdatePolicies": ["Sensor Update Policies:read"],
    # Device Control Policies operations
    "queryCombinedDeviceControlPolicyMembers": ["Device Control Policies:read"],
    "queryCombinedDeviceControlPolicies": ["Device Control Policies:read"],
    "getDefaultDeviceControlPolicies": ["Device Control Policies:read"],
    "updateDefaultDeviceControlPolicies": ["Device Control Policies:write"],
    "performDeviceControlPoliciesAction": ["Device Control Policies:write"],
    "patchDeviceControlPoliciesClassesV1": ["Device Control Policies:write"],
    "getDefaultDeviceControlSettings": ["Device Control Policies:read"],
    "updateDefaultDeviceControlSettings": ["Device Control Policies:write"],
    "setDeviceControlPoliciesPrecedence": ["Device Control Policies:write"],
    "getDeviceControlPolicies": ["Device Control Policies:read"],
    "createDeviceControlPolicies": ["Device Control Policies:write"],
    "updateDeviceControlPolicies": ["Device Control Policies:write"],
    "deleteDeviceControlPolicies": ["Device Control Policies:write"],
    "getDeviceControlPoliciesV2": ["Device Control Policies:read"],
    "postDeviceControlPoliciesV2": ["Device Control Policies:write"],
    "patchDeviceControlPoliciesV2": ["Device Control Policies:write"],
    "queryDeviceControlPolicyMembers": ["Device Control Policies:read"],
    "queryDeviceControlPolicies": ["Device Control Policies:read"],
    # Firewall Policies operations
    "queryCombinedFirewallPolicyMembers": ["Firewall Policies:read"],
    "queryCombinedFirewallPolicies": ["Firewall Policies:read"],
    "performFirewallPoliciesAction": ["Firewall Policies:write"],
    "setFirewallPoliciesPrecedence": ["Firewall Policies:write"],
    "getFirewallPolicies": ["Firewall Policies:read"],
    "createFirewallPolicies": ["Firewall Policies:write"],
    "updateFirewallPolicies": ["Firewall Policies:write"],
    "deleteFirewallPolicies": ["Firewall Policies:write"],
    "queryFirewallPolicyMembers": ["Firewall Policies:read"],
    "queryFirewallPolicies": ["Firewall Policies:read"],
    # Response Policies operations
    "queryCombinedRTResponsePolicyMembers": ["Response Policies:read"],
    "queryCombinedRTResponsePolicies": ["Response Policies:read"],
    "getRTResponsePolicies": ["Response Policies:read"],
    "queryRTResponsePolicyMembers": ["Response Policies:read"],
    "queryRTResponsePolicies": ["Response Policies:read"],
    "performRTResponsePoliciesAction": ["Response Policies:write"],
    "setRTResponsePoliciesPrecedence": ["Response Policies:write"],
    "createRTResponsePolicies": ["Response Policies:write"],
    "updateRTResponsePolicies": ["Response Policies:write"],
    "deleteRTResponsePolicies": ["Response Policies:write"],
    # Prevention Policies operations
    "queryCombinedPreventionPolicyMembers": ["Prevention Policies:read"],
    "queryCombinedPreventionPolicies": ["Prevention Policies:read"],
    "getPreventionPolicies": ["Prevention Policies:read"],
    "queryPreventionPolicyMembers": ["Prevention Policies:read"],
    "queryPreventionPolicies": ["Prevention Policies:read"],
    "performPreventionPoliciesAction": ["Prevention Policies:write"],
    "setPreventionPoliciesPrecedence": ["Prevention Policies:write"],
    "createPreventionPolicies": ["Prevention Policies:write"],
    "updatePreventionPolicies": ["Prevention Policies:write"],
    "deletePreventionPolicies": ["Prevention Policies:write"],
    # Workflows operations
    "WorkflowActivitiesCombined": ["Workflow:read"],
    "WorkflowActivitiesContentCombined": ["Workflow:read"],
    "WorkflowDefinitionsCombined": ["Workflow:read"],
    "WorkflowExecutionsCombined": ["Workflow:read"],
    "WorkflowTriggersCombined": ["Workflow:read"],
    "WorkflowDefinitionsExport": ["Workflow:read"],
    "WorkflowExecutionResults": ["Workflow:read"],
    "WorkflowGetHumanInputV1": ["Workflow:read"],
    "WorkflowDefinitionsAction": ["Workflow:write"],
    "WorkflowDefinitionsImport": ["Workflow:write"],
    "WorkflowDefinitionsUpdate": ["Workflow:write"],
    "WorkflowExecute": ["Workflow:write"],
    "WorkflowExecuteInternal": ["Workflow:write"],
    "WorkflowMockExecute": ["Workflow:write"],
    "WorkflowExecutionsAction": ["Workflow:write"],
    "WorkflowUpdateHumanInputV1": ["Workflow:write"],
    "WorkflowSystemDefinitionsDeProvision": ["Workflow:write"],
    "WorkflowSystemDefinitionsPromote": ["Workflow:write"],
    "WorkflowSystemDefinitionsProvision": ["Workflow:write"],
    # Quarantine operations
    "ActionUpdateCount": ["Quarantined Files:read"],
    "GetAggregateFiles": ["Quarantined Files:read"],
    "GetQuarantineFiles": ["Quarantined Files:read"],
    "QueryQuarantineFiles": ["Quarantined Files:read"],
    "UpdateQfByQuery": ["Quarantined Files:write"],
    "UpdateQuarantinedDetectsByIds": ["Quarantined Files:write"],
    # Serverless operations
    "GetCombinedVulnerabilitiesSARIF": ["Falcon Container Image:read"],
    # Scheduled Reports operations
    "scheduled_reports_query": ["Scheduled Reports:read"],
    "scheduled_reports_get": ["Scheduled Reports:read"],
    "scheduled_reports_launch": ["Scheduled Reports:read"],
    # Report Executions operations (same scope as Scheduled Reports)
    "report_executions_query": ["Scheduled Reports:read"],
    "report_executions_get": ["Scheduled Reports:read"],
    "report_executions_download_get": ["Scheduled Reports:read"],
    "report_executions_retry": ["Scheduled Reports:read"],
    # NGSIEM operations
    "GetDashboardTemplate": ["NGSIEM:read"],
    "CreateDashboardFromTemplate": ["NGSIEM:write"],
    "UpdateDashboardFromTemplate": ["NGSIEM:write"],
    "DeleteDashboard": ["NGSIEM:write"],
    "UploadLookupV1": ["NGSIEM:write"],
    "GetLookupV1": ["NGSIEM:read"],
    "GetLookupFromPackageV1": ["NGSIEM:read"],
    "GetLookupFromPackageWithNamespaceV1": ["NGSIEM:read"],
    "GetLookupFile": ["NGSIEM:read"],
    "CreateLookupFile": ["NGSIEM:write"],
    "UpdateLookupFile": ["NGSIEM:write"],
    "DeleteLookupFile": ["NGSIEM:write"],
    "GetParserTemplate": ["NGSIEM:read"],
    "CreateParserFromTemplate": ["NGSIEM:write"],
    "GetParser": ["NGSIEM:read"],
    "CreateParser": ["NGSIEM:write"],
    "UpdateParser": ["NGSIEM:write"],
    "DeleteParser": ["NGSIEM:write"],
    "GetSavedQueryTemplate": ["NGSIEM:read"],
    "CreateSavedQuery": ["NGSIEM:write"],
    "UpdateSavedQueryFromTemplate": ["NGSIEM:write"],
    "DeleteSavedQuery": ["NGSIEM:write"],
    "ListDashboards": ["NGSIEM:read"],
    "ListLookupFiles": ["NGSIEM:read"],
    "ListParsers": ["NGSIEM:read"],
    "ListSavedQueries": ["NGSIEM:read"],
    "StartSearchV1": ["NGSIEM:write"],
    "GetSearchStatusV1": ["NGSIEM:read"],
    "StopSearchV1": ["NGSIEM:write"],
    # Custom IOA operations
    "query_rule_groups_full": ["Custom IOA Rules:read"],
    "query_platformsMixin0": ["Custom IOA Rules:read"],
    "get_platformsMixin0": ["Custom IOA Rules:read"],
    "query_rule_types": ["Custom IOA Rules:read"],
    "get_rule_types": ["Custom IOA Rules:read"],
    "create_rule_groupMixin0": ["Custom IOA Rules:write"],
    "update_rule_groupMixin0": ["Custom IOA Rules:write"],
    "delete_rule_groupsMixin0": ["Custom IOA Rules:write"],
    "create_rule": ["Custom IOA Rules:write"],
    "update_rules_v2": ["Custom IOA Rules:write"],
    "delete_rules": ["Custom IOA Rules:write"],
    # Add more mappings as needed
}


def get_required_scopes(operation: str | None) -> list[str]:
    """Get the required API scopes for a specific operation.

    Args:
        operation: The API operation name

    Returns:
        List[str]: List of required API scopes
    """
    if operation is None:
        return []
    return API_SCOPE_REQUIREMENTS.get(operation, [])
